### ISSUE TITLE
No clear way to see if a Client fails

### ISSUE THREAD

**Issue by jaredmorrow** [helium/helium-ruby#18]
When creating a client connection, there is no way to know if the api key given works.  I found this out while trying to use a staging key against production.  The only way to find out is when there is an exception while trying to access data.  

I'm happy to fix, but don't know the most Ruby-idiomatic way.  Provide a `nil?` method?  Are exceptions good enough?

Example:

```
client = Helium::Client.new(api_key: 'badkey')
=> <Helium::Client @debug=false>
client.nil?
=> false
client.sensors
NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
from /Volumes/Data/development/helium/helium-ruby/lib/helium/resource.rb:29:in `all'
```

**Comment by allenan** [comment]
yeah i think it would need to be an exception at the point when you try to actually run something with the client. since it won't know until then if it can make a connection with that key.

**Comment by jaredmorrow** [comment]
That makes sense.  I wonder if a `ping` method would be handy for a cheap test of the key. That might be pointless anyway since we'd catch exceptions for the other calls anyway (for network failures and such).

**Comment by allenan** [comment]
I'm working on a general error handling PR, so I'll leave this open and close it when I finsh
