### ISSUE TITLE
POST timeseries data

### ISSUE THREAD

**Issue by allenan** [helium/helium-ruby#9]
https://docs.helium.com/api/v1/endpoints.html#post-sensor-id-timeseries
https://docs.helium.com/api/v1/endpoints.html#post-element-id-timeseries

**Comment by allenan** [comment]
@PharkMillups I have a stubbed out issue for this already in case you were looking to add an issue

**Comment by PharkMillups** [comment]
Glorious. I'll hold off. Thanks. Let me know what else I can do to help this along.

**Comment by allenan** [comment]
this is complete, will issue a new release of the gem
